/* The following code was generated by JFlex 1.4.3 on 14/04/15 21:43 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 14/04/15 21:43 from the specification file
 * <tt>compilador.fle</tt>
 */
class compilador {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int automata = 2;
  public static final int YYINITIAL = 0;
  public static final int transition = 4;
  public static final int expresion = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  0,  4,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     5,  7,  7,  0,  7,  0,  0,  6,  7,  7,  7,  7,  3,  0,  7,  7, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  2,  7, 27,  7,  7, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  7,  0,  7,  7,  0, 
     0, 14, 23,  1,  1,  9, 25, 10, 22, 24,  1,  1, 21, 18, 19, 17, 
    12,  1,  8, 20, 16, 15,  1,  1, 11,  1,  1, 13,  7, 26,  7,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\10\1\1\2\3\1\1\3\1\4\1\1\2\4"+
    "\1\5\16\0\2\4\7\0\1\6\2\0\2\4\11\0"+
    "\2\4\11\0\2\4\11\0\2\4\13\0\2\4\1\0"+
    "\1\7\6\0\1\10\4\0\1\4\4\0\1\11\6\0"+
    "\1\4\5\0\1\12\5\0\1\4\1\13\1\14\2\0"+
    "\1\15\21\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\34\0\70\0\124\0\160\0\214\0\250\0\304"+
    "\0\340\0\374\0\u0118\0\u0134\0\u0150\0\u016c\0\u0188\0\u01a4"+
    "\0\u01c0\0\u01dc\0\u01f8\0\u0214\0\u0230\0\160\0\u024c\0\u0268"+
    "\0\u0284\0\u02a0\0\u02bc\0\u02d8\0\u02f4\0\u016c\0\u0310\0\u032c"+
    "\0\u0348\0\u0364\0\u01f8\0\u0380\0\u039c\0\u03b8\0\u03d4\0\u03f0"+
    "\0\u040c\0\u0428\0\u0444\0\u0460\0\u047c\0\u0310\0\u0498\0\u04b4"+
    "\0\u04d0\0\u04ec\0\u0508\0\u0524\0\u0540\0\u055c\0\u0578\0\u0594"+
    "\0\u05b0\0\u05cc\0\u05e8\0\u0604\0\u0620\0\u063c\0\u0658\0\u0674"+
    "\0\u0690\0\u06ac\0\u06c8\0\u06e4\0\u0700\0\u071c\0\u0738\0\u0754"+
    "\0\u0770\0\u078c\0\u07a8\0\u07c4\0\u07e0\0\u07fc\0\u0818\0\u0834"+
    "\0\u0850\0\u086c\0\u0888\0\u08a4\0\u08c0\0\u08dc\0\u08f8\0\u0914"+
    "\0\u0930\0\u094c\0\u0968\0\u0984\0\u09a0\0\u09bc\0\u09d8\0\u09f4"+
    "\0\u0a10\0\u0a2c\0\u0a48\0\u0a64\0\u0a80\0\u0a9c\0\u0ab8\0\u0ad4"+
    "\0\160\0\u0af0\0\u0b0c\0\u0b28\0\u0b44\0\u0b60\0\214\0\u0b7c"+
    "\0\u0b98\0\u0bb4\0\160\0\u0bd0\0\u0bec\0\u0c08\0\u0c24\0\u0c40"+
    "\0\u0c5c\0\u0c78\0\u0c94\0\u0cb0\0\u0ccc\0\u0ce8\0\u0d04\0\160"+
    "\0\u0d20\0\u0d3c\0\u0d58\0\u0d74\0\u0d90\0\u0dac\0\u0dc8\0\160"+
    "\0\u0de4\0\u0e00\0\u0e1c\0\u0e38\0\u0e54\0\u0e70\0\250\0\u0e8c"+
    "\0\340\0\u0ea8\0\u0ec4\0\u0ee0\0\u0efc\0\u0f18\0\u0f34\0\u0f50"+
    "\0\u0f6c\0\u0f88\0\u0fa4\0\u0fc0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\10\5\1\6\5\5\1\7\25\5\1\6\5\5\1\10"+
    "\1\5\1\11\3\5\1\12\3\5\1\13\1\14\1\15"+
    "\2\5\1\16\6\5\1\17\4\16\1\5\1\20\13\16"+
    "\1\21\2\5\1\22\4\5\1\23\1\22\1\24\4\22"+
    "\1\5\1\25\13\22\1\26\1\5\45\0\1\27\41\0"+
    "\1\30\33\0\1\30\5\0\1\31\16\0\1\32\43\0"+
    "\1\33\36\0\1\34\40\0\1\35\35\0\1\15\2\0"+
    "\1\36\1\0\1\37\1\0\1\40\2\0\5\36\1\0"+
    "\14\36\3\0\1\36\1\0\1\37\1\0\1\40\2\0"+
    "\1\36\1\41\3\36\1\0\14\36\3\0\1\36\1\0"+
    "\1\37\1\0\1\40\2\0\5\36\1\0\1\36\1\42"+
    "\12\36\34\0\1\21\2\0\1\22\4\0\1\43\6\22"+
    "\1\0\14\22\3\0\1\44\6\0\5\44\1\0\14\44"+
    "\3\0\1\22\4\0\1\43\2\22\1\45\3\22\1\0"+
    "\14\22\3\0\1\22\4\0\1\43\6\22\1\0\1\22"+
    "\1\46\12\22\14\0\1\47\41\0\1\50\27\0\1\51"+
    "\35\0\1\52\33\0\1\53\45\0\1\54\26\0\1\55"+
    "\11\0\1\36\6\0\5\36\1\0\14\36\35\0\1\56"+
    "\1\0\1\36\1\0\1\37\1\0\1\40\2\0\2\36"+
    "\1\57\2\36\1\0\14\36\3\0\1\36\1\0\1\37"+
    "\1\0\1\40\2\0\5\36\1\0\2\36\1\60\11\36"+
    "\3\0\1\44\4\0\1\22\1\0\5\44\1\0\14\44"+
    "\3\0\1\22\4\0\1\43\3\22\1\61\2\22\1\0"+
    "\14\22\3\0\1\22\4\0\1\43\6\22\1\0\2\22"+
    "\1\62\11\22\13\0\1\63\43\0\1\64\40\0\1\65"+
    "\30\0\1\66\30\0\1\67\33\0\1\70\31\0\1\71"+
    "\16\0\1\36\1\0\1\37\1\0\1\40\2\0\1\36"+
    "\1\72\3\36\1\0\14\36\3\0\1\36\1\0\1\37"+
    "\1\0\1\40\2\0\5\36\1\0\3\36\1\73\10\36"+
    "\3\0\1\22\4\0\1\43\2\22\1\74\3\22\1\0"+
    "\14\22\3\0\1\22\4\0\1\43\6\22\1\0\3\22"+
    "\1\75\10\22\15\0\1\76\42\0\1\77\27\0\1\100"+
    "\41\0\1\101\20\0\1\102\52\0\1\103\30\0\1\104"+
    "\7\0\1\36\1\0\1\37\1\0\1\40\2\0\3\36"+
    "\1\105\1\36\1\0\14\36\3\0\1\36\1\0\1\37"+
    "\1\0\1\40\2\0\5\36\1\0\4\36\1\106\7\36"+
    "\3\0\1\22\4\0\1\43\4\22\1\107\1\22\1\0"+
    "\14\22\3\0\1\22\4\0\1\43\6\22\1\0\4\22"+
    "\1\110\7\22\16\0\1\111\35\0\1\112\44\0\1\113"+
    "\34\0\1\114\27\0\1\115\25\0\1\116\22\0\1\117"+
    "\27\0\1\36\1\0\1\37\1\0\1\40\2\0\4\36"+
    "\1\120\1\0\14\36\3\0\1\36\1\0\1\37\1\0"+
    "\1\40\2\0\5\36\1\0\1\121\13\36\3\0\1\22"+
    "\4\0\1\43\5\22\1\122\1\0\14\22\3\0\1\22"+
    "\4\0\1\43\6\22\1\0\1\123\13\22\3\0\1\124"+
    "\2\0\2\111\2\0\5\124\1\0\14\124\22\0\1\125"+
    "\24\0\1\126\42\0\1\127\20\0\1\130\53\0\1\131"+
    "\7\0\1\132\6\0\5\132\1\0\13\132\1\133\3\0"+
    "\1\134\1\0\1\37\1\111\1\135\2\0\5\134\1\0"+
    "\14\134\3\0\1\36\1\0\1\37\1\0\1\40\2\0"+
    "\5\36\1\0\2\36\1\136\11\36\3\0\1\137\2\0"+
    "\2\111\1\43\1\22\5\137\1\0\14\137\3\0\1\22"+
    "\4\0\1\43\6\22\1\0\2\22\1\140\11\22\3\0"+
    "\1\124\2\0\2\141\2\0\5\124\1\142\14\124\23\0"+
    "\1\143\32\0\1\144\43\0\1\145\4\0\1\146\6\0"+
    "\5\146\1\0\6\146\1\147\5\146\7\0\1\150\27\0"+
    "\1\132\1\151\1\152\4\0\5\132\1\0\14\132\3\0"+
    "\1\132\1\151\1\152\4\0\5\132\1\0\12\132\1\153"+
    "\1\132\3\0\1\134\1\0\1\37\1\141\1\154\2\0"+
    "\5\134\1\142\14\134\3\0\1\124\2\0\2\111\2\0"+
    "\5\124\1\0\14\124\1\0\1\56\1\0\1\36\1\0"+
    "\1\37\1\0\1\40\2\0\5\36\1\0\3\36\1\155"+
    "\10\36\3\0\1\137\2\0\2\141\1\43\1\22\5\137"+
    "\1\142\14\137\3\0\1\22\4\0\1\43\6\22\1\0"+
    "\3\22\1\156\10\22\6\0\2\141\7\0\1\142\26\0"+
    "\1\157\46\0\1\160\15\0\1\161\47\0\1\162\13\0"+
    "\1\146\1\163\1\164\4\0\5\146\1\0\14\146\3\0"+
    "\1\146\1\163\1\164\4\0\5\146\1\0\2\146\1\165"+
    "\11\146\3\0\1\166\6\0\5\166\1\0\12\166\1\167"+
    "\1\166\3\0\1\132\6\0\5\132\1\0\14\132\3\0"+
    "\1\132\1\151\1\152\4\0\5\132\1\0\5\132\1\170"+
    "\6\132\6\0\2\141\7\0\1\142\15\0\1\56\1\0"+
    "\1\36\1\0\1\37\1\0\1\40\2\0\5\36\1\0"+
    "\5\36\1\171\6\36\3\0\1\22\4\0\1\43\6\22"+
    "\1\0\5\22\1\172\6\22\3\0\1\173\2\0\2\160"+
    "\2\0\5\173\1\0\14\173\3\0\1\174\6\0\5\174"+
    "\1\0\1\175\13\174\25\0\1\176\11\0\1\146\6\0"+
    "\5\146\1\0\14\146\3\0\1\146\1\163\1\164\4\0"+
    "\5\146\1\0\1\177\13\146\3\0\1\166\1\200\1\201"+
    "\4\0\5\166\1\0\14\166\3\0\1\166\1\200\1\201"+
    "\4\0\5\166\1\0\5\166\1\202\6\166\3\0\1\132"+
    "\1\151\1\152\4\0\5\132\1\0\1\203\13\132\3\0"+
    "\1\204\1\0\1\37\1\160\1\205\2\0\5\204\1\0"+
    "\14\204\3\0\1\206\2\0\2\160\1\43\1\22\5\206"+
    "\1\0\14\206\3\0\1\173\6\0\5\173\1\207\14\173"+
    "\3\0\1\174\1\210\1\211\4\0\5\174\1\0\14\174"+
    "\3\0\1\174\1\210\1\211\4\0\5\174\1\0\7\174"+
    "\1\212\4\174\17\0\1\213\17\0\1\146\1\163\1\164"+
    "\4\0\5\146\1\0\2\146\1\214\11\146\3\0\1\166"+
    "\6\0\5\166\1\0\14\166\3\0\1\166\1\200\1\201"+
    "\4\0\5\166\1\0\12\166\1\215\1\166\3\0\1\132"+
    "\1\151\1\152\4\0\5\132\1\0\7\132\1\216\4\132"+
    "\3\0\1\204\1\0\1\37\1\0\1\40\2\0\5\204"+
    "\1\207\14\204\3\0\1\173\2\0\2\160\2\0\5\173"+
    "\1\0\14\173\1\0\1\56\1\0\1\206\4\0\1\43"+
    "\1\22\5\206\1\207\14\206\20\0\1\217\16\0\1\174"+
    "\6\0\5\174\1\0\14\174\3\0\1\174\1\210\1\211"+
    "\4\0\4\174\1\220\1\0\14\174\22\0\1\221\14\0"+
    "\1\146\1\163\1\164\4\0\1\146\1\222\3\146\1\0"+
    "\14\146\3\0\1\166\1\200\1\201\4\0\5\166\1\0"+
    "\2\166\1\223\11\166\3\0\1\132\1\151\1\152\1\0"+
    "\1\117\2\0\5\132\1\0\14\132\3\0\1\174\1\210"+
    "\1\211\4\0\5\174\1\0\10\174\1\224\3\174\3\0"+
    "\1\146\1\163\1\164\4\0\5\146\1\0\6\146\1\225"+
    "\5\146\3\0\1\166\1\200\1\201\4\0\5\166\1\0"+
    "\12\166\1\226\1\166\3\0\1\174\1\210\1\211\4\0"+
    "\5\174\1\0\1\227\13\174\3\0\1\146\1\163\1\164"+
    "\1\0\1\130\2\0\5\146\1\0\14\146\3\0\1\166"+
    "\1\200\1\201\4\0\5\166\1\0\1\230\13\166\3\0"+
    "\1\174\1\210\1\211\4\0\5\174\1\0\11\174\1\231"+
    "\2\174\3\0\1\166\1\200\1\201\4\0\5\166\1\0"+
    "\7\166\1\232\4\166\3\0\1\174\1\210\1\211\4\0"+
    "\1\174\1\233\3\174\1\0\14\174\3\0\1\166\1\200"+
    "\1\201\1\0\1\150\2\0\5\166\1\0\14\166\3\0"+
    "\1\174\1\210\1\211\4\0\5\174\1\0\2\174\1\234"+
    "\11\174\3\0\1\174\1\210\1\211\1\0\1\161\2\0"+
    "\5\174\1\0\14\174\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4060];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\20\1\1\11\16\0\2\1\7\0\1\1"+
    "\2\0\2\1\11\0\2\1\11\0\2\1\11\0\2\1"+
    "\13\0\2\1\1\0\1\1\6\0\1\11\4\0\1\1"+
    "\4\0\1\11\6\0\1\1\5\0\1\11\5\0\2\1"+
    "\1\11\2\0\1\1\21\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public int cont;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  compilador(java.io.Reader in) {
  	cont=0;
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  compilador(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	System.out.print("Naturales = "+cont);

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { System.out.println("estado a");
          }
        case 14: break;
        case 1: 
          { System.out.print(yytext());
          }
        case 15: break;
        case 8: 
          { System.out.println("final");
          }
        case 16: break;
        case 2: 
          { System.out.println("cierra automata");
	yybegin(YYINITIAL);
          }
        case 17: break;
        case 5: 
          { System.out.println("Fin de expresion regular");
		yybegin(YYINITIAL);
          }
        case 18: break;
        case 11: 
          { System.out.println("Dentro de automata");
yybegin(automata);
          }
        case 19: break;
        case 3: 
          { System.out.println("Cierra transition");
	yybegin(automata);
          }
        case 20: break;
        case 13: 
          { System.out.println("transition begins");
	yybegin(transition);
          }
        case 21: break;
        case 10: 
          { System.out.println("initial");
          }
        case 22: break;
        case 12: 
          { System.out.println("alphabet");
          }
        case 23: break;
        case 9: 
          { System.out.println("states");
          }
        case 24: break;
        case 4: 
          { System.out.println("Expresion Regular");
          }
        case 25: break;
        case 7: 
          { System.out.println("Dentro de expresion");
yybegin(expresion);
          }
        case 26: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java compilador <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        compilador scanner = null;
        try {
          scanner = new compilador( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
