
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 29 10:29:19 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 7;
  public static final int PUNTOYCOMA = 2;
  public static final int PAREN_D = 6;
  public static final int MAS = 3;
  public static final int error = 1;
  public static final int PAREN_I = 5;
  public static final int POR = 4;
  public static final int EOF = 0;
}

