
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 11 09:54:49 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AUTOMATA = 17;
  public static final int PARENTESIS_ABIERTO = 4;
  public static final int ASIGNADOR = 8;
  public static final int IGUAL = 11;
  public static final int NO_TERMINAL = 14;
  public static final int CORCHETE_CERRADO = 3;
  public static final int PALABRA_VACIA = 10;
  public static final int TRANSICION = 22;
  public static final int ALFABETO = 19;
  public static final int TERMINAL = 13;
  public static final int PARENTESIS_CERRADO = 5;
  public static final int COMA = 6;
  public static final int EOF = 0;
  public static final int INICIAL = 20;
  public static final int GRAMATICA = 12;
  public static final int UNION = 9;
  public static final int TEXTO = 23;
  public static final int FINAL = 21;
  public static final int error = 1;
  public static final int ESTADOS = 18;
  public static final int CORCHETE_ABIERTO = 2;
  public static final int PRODUCCION = 16;
  public static final int PUNTO_Y_COMA = 7;
  public static final int AXIOMA = 15;
}

