
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 11 02:24:07 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AUTOMATA = 15;
  public static final int ASIGNADOR = 6;
  public static final int IGUAL = 9;
  public static final int NO_TERMINAL = 12;
  public static final int CORCHETE_CERRADO = 3;
  public static final int PALABRA_VACIA = 8;
  public static final int TRANSICION = 20;
  public static final int ALFABETO = 17;
  public static final int TERMINAL = 11;
  public static final int COMA = 4;
  public static final int EOF = 0;
  public static final int INICIAL = 18;
  public static final int GRAMATICA = 10;
  public static final int UNION = 7;
  public static final int TEXTO = 21;
  public static final int FINAL = 19;
  public static final int error = 1;
  public static final int ESTADOS = 16;
  public static final int CORCHETE_ABIERTO = 2;
  public static final int PRODUCCION = 14;
  public static final int PUNTO_Y_COMA = 5;
  public static final int AXIOMA = 13;
}

