/* The following code was generated by JFlex 1.4.3 on 5/11/15 4:57 PM */

/* --------------------------Seccion codigo-usuario ------------------------ */
//import java_cup.runtime.Symbol;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/11/15 4:57 PM from the specification file
 * <tt>exprArit.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\61\1\3\1\0\2\61\22\0\1\61\3\0\1\15\2\0"+
    "\1\41\1\6\1\7\1\2\1\46\1\10\1\45\1\0\1\1\12\60"+
    "\1\12\1\11\1\0\1\13\1\0\1\47\1\42\1\54\2\57\1\56"+
    "\1\52\1\53\7\57\1\55\3\57\1\51\10\57\1\43\1\0\1\44"+
    "\3\0\1\20\1\37\1\34\1\32\1\23\1\40\1\16\1\36\1\24"+
    "\2\57\1\26\1\21\1\25\1\27\1\31\1\57\1\17\1\35\1\22"+
    "\1\33\2\57\1\30\1\57\1\50\1\4\1\14\1\5\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\1\1\12\1\13\1\14\12\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\2\15\1\25"+
    "\1\0\1\26\17\27\1\30\1\0\17\27\1\31\23\27"+
    "\1\32\7\27\1\33\3\27\1\34\10\27\1\35\1\36"+
    "\1\27\1\37\5\27\1\40\4\27\1\41\2\27\1\42"+
    "\2\27\1\43\1\44\1\45\3\27\1\46\2\27\1\47"+
    "\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\62\0\62\0\62\0\62\0\62"+
    "\0\62\0\62\0\62\0\226\0\62\0\62\0\62\0\310"+
    "\0\372\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\62\0\62\0\62\0\62\0\62\0\62\0\62"+
    "\0\u02bc\0\u02ee\0\u0320\0\u0352\0\62\0\u015e\0\u0384\0\u03b6"+
    "\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546"+
    "\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0320\0\u0640\0\u0672\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834"+
    "\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0352\0\u0960\0\u0992"+
    "\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22"+
    "\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2"+
    "\0\u0ce4\0\u015e\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\u0e10"+
    "\0\u0e42\0\u015e\0\u0e74\0\u0ea6\0\u0ed8\0\u015e\0\u0f0a\0\u0f3c"+
    "\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004\0\u1036\0\u1068\0\u015e\0\u015e"+
    "\0\u109a\0\u015e\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u015e"+
    "\0\u11c6\0\u11f8\0\u122a\0\u125c\0\u015e\0\u128e\0\u12c0\0\u015e"+
    "\0\u12f2\0\u1324\0\u015e\0\u015e\0\u015e\0\u1356\0\u1388\0\u13ba"+
    "\0\u015e\0\u13ec\0\u141e\0\u015e\0\u015e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\23\1\25\1\26\3\23\1\27"+
    "\3\23\1\30\2\23\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\23\1\41\1\23\1\42\4\23"+
    "\1\43\1\5\64\0\1\44\72\0\1\45\64\0\1\46"+
    "\1\47\21\46\7\0\11\46\17\0\5\46\1\50\15\46"+
    "\7\0\11\46\17\0\10\46\1\51\1\46\1\52\2\46"+
    "\1\53\5\46\7\0\11\46\17\0\23\46\7\0\11\46"+
    "\17\0\1\46\1\54\3\46\1\55\15\46\7\0\11\46"+
    "\17\0\7\46\1\56\13\46\7\0\11\46\17\0\11\46"+
    "\1\57\11\46\7\0\11\46\17\0\1\46\1\60\21\46"+
    "\7\0\11\46\17\0\4\46\1\61\16\46\7\0\11\46"+
    "\17\0\6\46\1\62\14\46\7\0\11\46\17\0\23\46"+
    "\7\0\2\46\1\63\6\46\17\0\23\46\7\0\4\46"+
    "\1\64\4\46\17\0\23\65\7\0\11\65\1\0\2\44"+
    "\1\66\1\0\56\44\16\0\2\46\1\67\20\46\7\0"+
    "\11\46\17\0\1\70\15\46\1\71\4\46\7\0\11\46"+
    "\17\0\13\46\1\72\7\46\7\0\11\46\17\0\6\46"+
    "\1\73\14\46\7\0\11\46\17\0\4\46\1\74\16\46"+
    "\7\0\11\46\17\0\2\46\1\75\20\46\7\0\11\46"+
    "\17\0\1\46\1\76\21\46\7\0\11\46\17\0\6\46"+
    "\1\77\14\46\7\0\11\46\17\0\7\46\1\100\13\46"+
    "\7\0\11\46\17\0\11\46\1\101\11\46\7\0\11\46"+
    "\17\0\2\46\1\102\20\46\7\0\11\46\17\0\7\46"+
    "\1\103\13\46\7\0\11\46\17\0\4\46\1\104\16\46"+
    "\7\0\11\46\17\0\4\46\1\105\16\46\7\0\11\46"+
    "\1\0\1\44\1\106\1\66\1\0\56\44\16\0\3\46"+
    "\1\107\17\46\7\0\11\46\17\0\5\46\1\110\15\46"+
    "\7\0\11\46\17\0\11\46\1\111\11\46\7\0\11\46"+
    "\17\0\20\46\1\112\2\46\7\0\11\46\17\0\11\46"+
    "\1\113\11\46\7\0\11\46\17\0\11\46\1\114\11\46"+
    "\7\0\11\46\17\0\7\46\1\115\13\46\7\0\11\46"+
    "\17\0\3\46\1\116\17\46\7\0\11\46\17\0\4\46"+
    "\1\117\16\46\7\0\11\46\17\0\4\46\1\120\16\46"+
    "\7\0\11\46\17\0\14\46\1\121\6\46\7\0\11\46"+
    "\17\0\4\46\1\122\16\46\7\0\11\46\17\0\2\46"+
    "\1\123\20\46\7\0\11\46\17\0\11\46\1\124\11\46"+
    "\7\0\11\46\17\0\11\46\1\125\11\46\7\0\11\46"+
    "\17\0\3\46\1\126\17\46\7\0\11\46\17\0\12\46"+
    "\1\127\10\46\7\0\11\46\17\0\1\130\22\46\7\0"+
    "\11\46\17\0\2\46\1\131\20\46\7\0\11\46\17\0"+
    "\3\46\1\132\17\46\7\0\11\46\17\0\3\46\1\133"+
    "\17\46\7\0\11\46\17\0\17\46\1\134\3\46\7\0"+
    "\11\46\17\0\6\46\1\135\14\46\7\0\11\46\17\0"+
    "\6\46\1\136\14\46\7\0\11\46\17\0\5\46\1\137"+
    "\15\46\7\0\11\46\17\0\15\46\1\140\5\46\7\0"+
    "\11\46\17\0\5\46\1\141\15\46\7\0\11\46\17\0"+
    "\10\46\1\142\12\46\7\0\11\46\17\0\23\46\7\0"+
    "\3\46\1\143\5\46\17\0\23\46\7\0\5\46\1\144"+
    "\3\46\17\0\2\46\1\145\20\46\7\0\11\46\17\0"+
    "\13\46\1\146\7\46\7\0\11\46\17\0\7\46\1\147"+
    "\13\46\7\0\11\46\17\0\21\46\1\150\1\46\7\0"+
    "\11\46\17\0\2\46\1\151\20\46\7\0\11\46\17\0"+
    "\6\46\1\152\14\46\7\0\11\46\17\0\7\46\1\153"+
    "\13\46\7\0\11\46\17\0\2\46\1\154\20\46\7\0"+
    "\11\46\17\0\1\46\1\155\21\46\7\0\11\46\17\0"+
    "\16\46\1\156\4\46\7\0\11\46\17\0\17\46\1\157"+
    "\3\46\7\0\11\46\17\0\23\46\7\0\4\46\1\160"+
    "\4\46\17\0\23\46\7\0\6\46\1\161\2\46\17\0"+
    "\1\46\1\162\21\46\7\0\11\46\17\0\6\46\1\163"+
    "\14\46\7\0\11\46\17\0\5\46\1\164\15\46\7\0"+
    "\11\46\17\0\4\46\1\165\16\46\7\0\11\46\17\0"+
    "\4\46\1\166\16\46\7\0\11\46\17\0\2\46\1\167"+
    "\20\46\7\0\11\46\17\0\10\46\1\170\12\46\7\0"+
    "\11\46\17\0\3\46\1\171\17\46\7\0\11\46\17\0"+
    "\4\46\1\172\16\46\7\0\11\46\17\0\23\46\7\0"+
    "\3\46\1\173\5\46\17\0\23\46\7\0\1\174\10\46"+
    "\17\0\4\46\1\175\16\46\7\0\11\46\17\0\11\46"+
    "\1\176\11\46\7\0\11\46\17\0\6\46\1\177\14\46"+
    "\7\0\11\46\17\0\10\46\1\200\12\46\7\0\11\46"+
    "\17\0\6\46\1\201\14\46\7\0\11\46\17\0\6\46"+
    "\1\202\14\46\7\0\11\46\17\0\23\46\7\0\4\46"+
    "\1\203\4\46\17\0\5\46\1\204\15\46\7\0\11\46"+
    "\17\0\7\46\1\205\13\46\7\0\11\46\17\0\11\46"+
    "\1\206\11\46\7\0\11\46\17\0\7\46\1\207\13\46"+
    "\7\0\11\46\17\0\11\46\1\210\11\46\7\0\11\46"+
    "\17\0\7\46\1\211\13\46\7\0\11\46\17\0\2\46"+
    "\1\212\20\46\7\0\11\46\17\0\7\46\1\213\13\46"+
    "\7\0\11\46\17\0\10\46\1\214\12\46\7\0\11\46"+
    "\17\0\17\46\1\215\3\46\7\0\11\46\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\10\11\1\1\3\11\12\1\7\11"+
    "\3\1\1\0\1\11\20\1\1\0\127\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return new Symbol(sym.IGUAL);
          }
        case 41: break;
        case 18: 
          { return new Symbol(sym.GUION);
          }
        case 42: break;
        case 21: 
          { return new Symbol(sym.CARACTER_NUMERO, new String(yytext()));
          }
        case 43: break;
        case 2: 
          { return new Symbol(sym.CLAUSURA);
          }
        case 44: break;
        case 31: 
          { return new Symbol(sym.GRAMATICA);
          }
        case 45: break;
        case 39: 
          { return new Symbol(sym.NO_TERMINAL);
          }
        case 46: break;
        case 5: 
          { return new Symbol(sym.CORCHETE_CERRADO);
          }
        case 47: break;
        case 37: 
          { return new Symbol(sym.AUTOMATA);
          }
        case 48: break;
        case 36: 
          { return new Symbol(sym.RECONOCER);
          }
        case 49: break;
        case 22: 
          { return new Symbol(sym.ASIGNADOR);
          }
        case 50: break;
        case 29: 
          { return new Symbol(sym.ESTADOS);
          }
        case 51: break;
        case 32: 
          { return new Symbol(sym.INICIAL);
          }
        case 52: break;
        case 4: 
          { return new Symbol(sym.CORCHETE_ABIERTO);
          }
        case 53: break;
        case 1: 
          { System.err.println("Caracter Ilegal: "+yytext());
          }
        case 54: break;
        case 17: 
          { return new Symbol(sym.P_CUADRADO_CERRADO);
          }
        case 55: break;
        case 12: 
          { return new Symbol(sym.PALABRA_VACIA);
          }
        case 56: break;
        case 15: 
          { return new Symbol(sym.LENGUAJE_VACIO);
          }
        case 57: break;
        case 3: 
          { /* ignora delimitadores */
          }
        case 58: break;
        case 19: 
          { return new Symbol(sym.CLAUSURA_POSITIVA);
          }
        case 59: break;
        case 16: 
          { return new Symbol(sym.P_CUADRADO_ABIERTO);
          }
        case 60: break;
        case 13: 
          { return new Symbol(sym.CARACTER, new String(yytext()));
          }
        case 61: break;
        case 34: 
          { return new Symbol(sym.TERMINAL);
          }
        case 62: break;
        case 40: 
          { return new Symbol(sym.PRODUCCION);
          }
        case 63: break;
        case 11: 
          { return new Symbol(sym.UNION);
          }
        case 64: break;
        case 23: 
          { return new Symbol(sym.IDENTIFICADOR, new String(yytext()));
          }
        case 65: break;
        case 20: 
          { return new Symbol(sym.INTERROGACION);
          }
        case 66: break;
        case 8: 
          { return new Symbol(sym.COMA);
          }
        case 67: break;
        case 35: 
          { return new Symbol(sym.FATONDFA);
          }
        case 68: break;
        case 9: 
          { return new Symbol(sym.PUNTO_Y_COMA);
          }
        case 69: break;
        case 26: 
          { return new Symbol(sym.AXIOMA);
          }
        case 70: break;
        case 7: 
          { return new Symbol(sym.PARENTESIS_CERRADO);
          }
        case 71: break;
        case 33: 
          { return new Symbol(sym.ALFABETO);
          }
        case 72: break;
        case 14: 
          { return new Symbol(sym.COMILLA);
          }
        case 73: break;
        case 38: 
          { return new Symbol(sym.TRANSICION);
          }
        case 74: break;
        case 30: 
          { return new Symbol(sym.RETOFA);
          }
        case 75: break;
        case 6: 
          { return new Symbol(sym.PARENTESIS_ABIERTO);
          }
        case 76: break;
        case 28: 
          { return new Symbol(sym.EXPRESION_REGULAR);
          }
        case 77: break;
        case 27: 
          { return new Symbol(sym.FINAL);
          }
        case 78: break;
        case 24: 
          { return new Symbol(sym.CARACTERES_NUMEROS, new String(yytext()));
          }
        case 79: break;
        case 25: 
          { 
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
